import type { Metadata } from "next";

import { Header } from "@/components/shared/header";

import "./globals.css";

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"flex h-screen flex-col gap-8 p-4"}>{children}</body>
    </html>
  );
}
